sonar.projectKey=ecommerce-devsecops
sonar.projectName=E-Commerce Enterprise DevSecOps Pipeline
sonar.projectVersion=1.0.0

# Path to source files
sonar.sources=app/backend,app/frontend

# Path to test files
sonar.tests=app/tests

# Technical configurations
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=**/tests/**,**/node_modules/**,**/terraform/**,**/kubernetes/**
